DROP TABLE IF EXISTS FAVORIS;
DROP TABLE IF EXISTS SUIVRE;
DROP TABLE IF EXISTS ETRE_SUIVI_PAR;
DROP TABLE IF EXISTS PHOTO;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CLIENT;

-- Création de la table CLIENT
CREATE TABLE CLIENT (
    Pseudo VARCHAR(22) PRIMARY KEY ,
    Email VARCHAR(50), 
    Mdp VARCHAR(50)
);